stages:
  - build

before_script:
  - hostname
  - whoami
# - pwd

build-linux-gcc:
  stage: build
  tags:
   - build-linux
  script:
#   - git submodule update --init --recursive
    - git submodule update --init -- conf
    - git submodule update --init -- lib/MIPP
    - mkdir build
    - cd build
    - cmake .. -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release -DENABLE_GSL=ON -DCMAKE_CXX_FLAGS="-Wall -funroll-loops -march=native -DMULTI_PREC"
    - make
    - ./bin/aff3ct --version
    - ./bin/aff3ct -C POLAR -m 1.0 -M 3.5 -s 0.25 -K 1755 -N 2048 --crc-poly 32-GZIP --dec-type ASCL

build-linux-clang:
  stage: build
  tags:
   - build-linux
  script:
#   - git submodule update --init --recursive
    - git submodule update --init -- conf
    - git submodule update --init -- lib/MIPP
    - mkdir build
    - cd build
    - cmake .. -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DENABLE_GSL=ON -DCMAKE_CXX_FLAGS="-Wall -funroll-loops -march=native -DMULTI_PREC"
    - make
    - ./bin/aff3ct --version
    - ./bin/aff3ct -C POLAR -m 1.0 -M 3.5 -s 0.25 -K 1755 -N 2048 --crc-poly 32-GZIP --dec-type ASCL

build-windows-gcc:
  stage: build
  tags:
   - build-windows
  script:
    - set PATH=%PATH%;C:\Program Files\Git\cmd
    - set PATH=%PATH%;C:\Program Files\CMake\bin
    - set PATH=%PATH%;C:\Program Files\Git\mingw64\bin
#   - git submodule update --init --recursive
    - git submodule update --init -- conf
    - git submodule update --init -- lib/MIPP
    - mkdir build
    - cd build
    - cmake .. -G"MinGW Makefiles" -DCMAKE_CXX_COMPILER=g++.exe -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall -funroll-loops -march=native -DMULTI_PREC"
    - mingw32-make
    - cd bin
    - aff3ct.exe --version
    - aff3ct.exe -C POLAR -m 1.0 -M 3.5 -s 0.25 -K 1755 -N 2048 --crc-poly 32-GZIP --dec-type ASCL

build-windows-msvc:
  stage: build
  tags:
   - build-windows
  script:
    - set PATH=%PATH%;C:\Program Files\Git\cmd
    - set PATH=%PATH%;C:\Program Files\CMake\bin
    - set PATH=%PATH%;C:\Program Files\Git\mingw64\bin
    - set "VSCMD_START_DIR=%CD%"
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
#   - git submodule update --init --recursive
    - git submodule update --init -- conf
    - git submodule update --init -- lib/MIPP
    - mkdir build
    - cd build
    - cmake .. -G"Visual Studio 15 2017 Win64" -DCMAKE_CXX_FLAGS="-D_CRT_SECURE_NO_DEPRECATE -DMULTI_PREC /EHsc /arch:AVX"
    - devenv /build Release aff3ct.sln
    - cd bin\Release
    - aff3ct.exe --version
    - aff3ct.exe -C POLAR -m 1.0 -M 3.5 -s 0.25 -K 1755 -N 2048 --crc-poly 32-GZIP --dec-type ASCL