stages:
  - analyse
  - build
  - test

before_script:
  - hostname
  - whoami
# - pwd
  - git submodule sync --recursive
  - git submodule update --init --recursive

analyse-cppcheck:
  stage: analyse
  artifacts:
     name: analyse-cppcheck-logs
     when: always
     paths:
       - cppcheck/
  tags: 
    - cppcheck
  script:
    - ./ci/analyse-cppcheck.sh

analyse-sonarqube:
  stage: analyse
  tags: 
    - sonarqube
  only:
    - master
  script:
    - ./ci/analyse-sonarqube.sh

build-linux-gcc:
  stage: build
  tags:
   - linux
  script:
    - ./ci/build-linux-gcc.sh

build-linux-clang:
  stage: build
  tags:
   - linux
  script:
    - ./ci/build-linux-clang.sh

build-linux-gcc-4.8:
  stage: build
  tags:
   - linux
  script:
    - ./ci/build-linux-gcc-4.8.sh

build-windows-gcc:
  stage: build
  tags:
   - windows
  script:
    - ./ci/build-windows-gcc.bat

build-windows-msvc:
  stage: build
  tags:
   - windows
  script:
    - ./ci/build-windows-msvc.bat

build-mac-osx-clang:
  stage: build
  tags:
   - mac-osx
  script:
    - ./ci/build-mac-osx-clang.sh

test-regression:
  stage: test
  tags:
    - test
  artifacts:
     name: test-regression-results
     when: always
     paths:
       - tests/results/
  script:
    - ./ci/test-build-linux-gcc.sh
    - cd tests
    - ./tests.py --max-snr-time 5 --sensibility 2.5 --weak-rate 0.9 --verbose 1