stages:
  - analysis
  - build
  - test
  - coverage
  - sonarqube

before_script:
  - hostname
  - whoami
# - pwd
  - git submodule sync --recursive
  - git submodule update --init --recursive

analysis-cppcheck:
  stage: analysis
  artifacts:
    name: analysis-cppcheck-logs
    when: always
    paths:
      - cppcheck/
  tags:
    - cppcheck
  script:
    - ./ci/analysis-cppcheck.sh

build-linux-gcc:
  stage: build
  tags:
    - linux
    - gcc
  script:
    - ./ci/build-linux-gcc.sh

build-linux-gcc-8-bit:
  stage: build
  tags:
    - linux
    - gcc
    - arm32
    - cmake
    - gsl
  script:
    - ./ci/build-linux-gcc-8-bit.sh

build-linux-gcc-mpi:
  stage: build
  tags:
    - linux
    - gcc
    - mpi
    - cmake
    - gsl
  script:
    - ./ci/build-linux-gcc-mpi.sh

build-linux-gcc-systemc:
  stage: build
  tags:
    - linux
    - gcc
    - systemc
    - cmake
  script:
    - ./ci/build-linux-gcc-systemc.sh

build-linux-clang:
  stage: build
  tags:
    - linux
    - clang
    - cmake
    - x86
    - gsl
  script:
    - ./ci/build-linux-clang.sh

build-linux-gcc-4.8:
  stage: build
  tags:
    - linux
    - gcc-4.8
    - cmake
    - gsl
  script:
    - ./ci/build-linux-gcc-4.8.sh

build-linux-icpc:
  stage: build
  tags:
    - linux
    - icpc
    - cmake
    - mkl
    - gsl
  script:
    - ./ci/build-linux-icpc.sh

build-coverage-linux-gcc:
  stage: build
  tags:
    - linux
    - gcc
    - cmake
    - sse4.2
  artifacts:
    paths:
      - build_coverage_linux_x86_gcc/bin/
      - build_coverage_linux_x86_gcc/CMakeFiles.tar.gz
  script:
    - ./ci/build-coverage-linux-gcc.sh

build-test-linux-gcc:
  stage: build
  tags:
    - linux
    - gcc
    - sse4.2
    - cmake
    - gsl
  artifacts:
    paths:
      - build_test_linux_x86_gcc/bin/
  script:
    - ./ci/build-test-linux-gcc.sh

build-windows-gcc:
  stage: build
  tags:
    - windows
    - gcc
    - cmake
  script:
    - ./ci/build-windows-gcc.bat

build-windows-msvc:
  stage: build
  tags:
    - windows
    - msvc
    - cmake
  script:
    - ./ci/build-windows-msvc.bat

build-mac-osx-clang:
  stage: build
  tags:
    - mac-osx
    - apple-clang
    - cmake
  script:
    - ./ci/build-mac-osx-clang.sh

test-regression:
  stage: test
  retry: 1
  tags:
    - linux
    - gcc
    - sse4.2
    - powerful
    - python
  artifacts:
     name: test-regression-results
     when: always
     paths:
      - build_test_linux_x86_gcc/bin/
      - test-regression-results/
  script:
    - ./ci/test-regression.py --build-path build_test_linux_x86_gcc --max-snr-time 5 --sensibility 2.5 --weak-rate 0.9 --verbose 1

test-coverage-regression:
  stage: test
  tags:
    - linux
    - lcov
    - sse4.2
    - powerful
  artifacts:
     name: code_coverage_files
     when: always
     paths:
      - build_coverage_linux_x86_gcc/bin/
      - build_coverage_linux_x86_gcc/CMakeFiles.tar.gz
      - code_coverage_files/
  script:
    - ./ci/test-coverage-regression.sh

coverage-linux:
  stage: coverage
  tags:
    - linux
    - lcov
    - lcov_cobertura
  coverage: '/.*lines\.*: (\d+.\d+\%)/'
  artifacts:
     name: code_coverage_report
     when: always
     paths:
       - code_coverage_files/
       - code_coverage_report/
  script:
    - ./ci/coverage-linux.sh

sonarqube-linux:
  stage: sonarqube
  tags:
    - sonarqube
  only:
    - master
    - development
  artifacts:
    paths:
      - cppcheck/
      - code_coverage_files/
  script:
    - ./ci/sonarqube-linux.sh