stages:
  - analysis
  - build
  - test
  - coverage

before_script:
  - hostname
  - whoami
# - pwd
  - git submodule sync --recursive
  - git submodule update --init --recursive

analysis-cppcheck:
  stage: analysis
  artifacts:
    name: analysis-cppcheck-logs
    when: always
    paths:
      - cppcheck/
  tags:
    - cppcheck
  script:
    - ./ci/analysis-cppcheck.sh

analysis-sonarqube:
  stage: analysis
  tags:
    - sonarqube
  only:
    - master
  script:
    - ./ci/analysis-sonarqube.sh

build-linux-gcc:
  stage: build
  tags:
    - linux
    - gcc
  script:
    - ./ci/build-linux-gcc.sh

build-linux-gcc-8-bit:
  stage: build
  tags:
    - linux
    - gcc
    - arm32
  script:
    - ./ci/build-linux-gcc-8-bit.sh

build-linux-gcc-mpi:
  stage: build
  tags:
    - linux
    - gcc
    - mpi
  script:
    - ./ci/build-linux-gcc-mpi.sh

build-linux-gcc-systemc:
  stage: build
  tags:
    - linux
    - gcc
    - systemc
  script:
    - ./ci/build-linux-gcc-systemc.sh

build-linux-clang:
  stage: build
  tags:
    - linux
    - clang
  script:
    - ./ci/build-linux-clang.sh

build-linux-gcc-4.8:
  stage: build
  tags:
    - linux
    - gcc-4.8
  script:
    - ./ci/build-linux-gcc-4.8.sh

build-linux-icpc:
  stage: build
  tags:
    - linux
    - icpc
  script:
    - ./ci/build-linux-icpc.sh

build-windows-gcc:
  stage: build
  tags:
    - windows
    - gcc
  script:
    - ./ci/build-windows-gcc.bat

build-windows-msvc:
  stage: build
  tags:
    - windows
    - msvc
  script:
    - ./ci/build-windows-msvc.bat

build-mac-osx-clang:
  stage: build
  tags:
    - mac-osx
    - apple-clang
  script:
    - ./ci/build-mac-osx-clang.sh

test-regression:
  stage: test
  retry: 1
  tags:
    - linux
    - gcc
    - powerful
  artifacts:
     name: test-regression-results
     when: always
     paths:
       - test-regression-results/
  script:
    - ./ci/test-build-linux-gcc.sh
    - ./ci/test-regression.py --max-snr-time 5 --sensibility 2.5 --weak-rate 0.9 --verbose 1

coverage-linux-gcc:
  stage: coverage
  tags:
    - linux
    - gcc
    - coverage
  coverage: '/.*lines\.*: (\d+.\d+\%)/'
  artifacts:
     name: code_coverage_report
     when: always
     paths:
       - code_coverage_files/
       - code_coverage_report/
  script:
    - ./ci/coverage-linux-gcc.sh